"""Hằng số label/mode cho các memory decision task của Nimble."""

MEMORY_SKIP = "skip"
MEMORY_RETRIEVE = "retrieve"
MEMORY_LIST_FACTS = "list_facts"
MEMORY_RECENT_EPISODES = "recent_episodes"
MEMORY_REMEMBER = "remember"
MEMORY_DISCARD = "discard"
MEMORY_SEMANTIC_FACT = "semantic_fact"
MEMORY_EPISODIC_EVENT = "episodic_event"
MEMORY_CORRECTION_NONE = "none"
MEMORY_CORRECT_MEMORY = "correct_memory"
MEMORY_FORGET_MEMORY = "forget_memory"
MEMORY_TARGET_FACT = "fact"
MEMORY_TARGET_EPISODE = "episode"
MEMORY_TARGET_UNKNOWN = "unknown"
MEMORY_RETRIEVAL_SEARCH = "search"
MEMORY_RETRIEVAL_LIST = "list"
MEMORY_RETRIEVAL_RECENT = "recent"
MEMORY_RETRIEVAL_NONE = "none"
QUESTION_NAME = "memory_retrieval"
WRITE_QUESTION_NAME = "memory_write"
CANDIDATE_QUESTION_NAME = "memory_type"
CORRECTION_QUESTION_NAME = "memory_correction"
MAX_MEMORY_GATE_PROMPT_LENGTH = 1600
